import { useState } from "react";
import { Hash, Pencil, Plus, Settings, Shield, Trash2, Users, Volume2, X } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { CUSTOM_PERMISSION_LABEL, CUSTOM_PERMISSIONS, ROLE_LABEL, ROLE_ORDER, ROLE_STYLE, topRole, type AppRole, type CustomPermission } from "@/lib/espancord";

const db = supabase as any;
const field = "w-full rounded-lg border border-input bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary/30";

type Channel = { id: string; name: string; type: "texto" | "voz"; min_role: AppRole; position: number };
type Role = { id: string; name: string; color: string; position: number; permissions: CustomPermission[] };
type Member = { id: string; display_name: string; avatar_url: string | null; roles: AppRole[]; customRoles: Role[]; status: "active" | "kicked" | "banned" };
type SettingsData = { name: string; description: string; accent_color: string };
export type AdminTab = "server" | "channels" | "roles" | "members";

export function ServerAdmin({ initialTab, channels, channelAccess, roles, members, server, canServer, canChannels, canRoles, onClose, onRefresh, onMember }: {
  initialTab: AdminTab; channels: Channel[]; channelAccess: Record<string,string[]>; roles: Role[]; members: Member[]; server: SettingsData;
  canServer: boolean; canChannels: boolean; canRoles: boolean; onClose: () => void; onRefresh: () => void; onMember: (id:string) => void;
}) {
  const fallback: AdminTab = canServer ? "server" : canChannels ? "channels" : canRoles ? "roles" : "members";
  const [tab,setTab] = useState<AdminTab>(initialTab ?? fallback);
  const [settings,setSettings] = useState(server);
  const [channelId,setChannelId] = useState<string|null>(null);
  const [channelName,setChannelName] = useState("");
  const [channelType,setChannelType] = useState<"texto"|"voz">("texto");
  const [minRole,setMinRole] = useState<AppRole>("membro");
  const [allowed,setAllowed] = useState<string[]>([]);
  const [roleId,setRoleId] = useState<string|null>(null);
  const [roleName,setRoleName] = useState("");
  const [roleColor,setRoleColor] = useState("#36d576");
  const [permissions,setPermissions] = useState<CustomPermission[]>([]);

  async function saveServer(){ const {error}=await db.from("server_settings").update(settings).eq("id",1); if(error) toast.error("Não foi possível salvar."); else { toast.success("Servidor atualizado."); onRefresh(); } }
  function resetChannel(){ setChannelId(null); setChannelName(""); setChannelType("texto"); setMinRole("membro"); setAllowed([]); }
  function editChannel(c:Channel){ setChannelId(c.id); setChannelName(c.name); setChannelType(c.type); setMinRole(c.min_role); setAllowed(channelAccess[c.id]??[]); setTab("channels"); }
  async function saveChannel(){
    if(!channelName.trim()) return;
    const payload={name:channelName.toLowerCase().trim().replace(/\s+/g,"-"),type:channelType,min_role:minRole,position:channelId?channels.find(c=>c.id===channelId)?.position??0:channels.length+1};
    let id=channelId;
    if(id){ const {error}=await supabase.from("channels").update(payload).eq("id",id); if(error){toast.error("Não foi possível editar o canal.");return;} }
    else { const {data,error}=await supabase.from("channels").insert(payload).select("id").single(); if(error||!data){toast.error("Não foi possível criar o canal.");return;} id=data.id; }
    const clear=await db.from("channel_role_access").delete().eq("channel_id",id);
    if(!clear.error && allowed.length){ const access=await db.from("channel_role_access").insert(allowed.map(role_id=>({channel_id:id,role_id}))); if(access.error) toast.error("Canal salvo, mas a restrição por cargo falhou."); }
    toast.success(channelId?"Canal atualizado.":"Canal criado."); resetChannel(); onRefresh();
  }
  async function removeChannel(id:string){ const {error}=await supabase.from("channels").delete().eq("id",id); if(error) toast.error("Não foi possível excluir."); else { if(channelId===id) resetChannel(); onRefresh(); } }
  function resetRole(){ setRoleId(null); setRoleName(""); setRoleColor("#36d576"); setPermissions([]); }
  function editRole(r:Role){ setRoleId(r.id); setRoleName(r.name); setRoleColor(r.color); setPermissions(r.permissions); setTab("roles"); }
  async function saveRole(){ if(!roleName.trim()) return; const payload={name:roleName.trim(),color:roleColor,permissions}; const res=roleId?await db.from("server_roles").update(payload).eq("id",roleId):await db.from("server_roles").insert({...payload,position:roles.length+1}); if(res.error) toast.error("Não foi possível salvar o cargo."); else {toast.success(roleId?"Cargo atualizado.":"Cargo criado.");resetRole();onRefresh();} }
  async function removeRole(id:string){ const {error}=await db.from("server_roles").delete().eq("id",id); if(error) toast.error("Não foi possível excluir o cargo."); else {resetRole();onRefresh();} }

  const tabs=[{id:"server" as const,label:"Visão geral",show:canServer},{id:"channels" as const,label:"Canais",show:canChannels},{id:"roles" as const,label:"Cargos",show:canRoles},{id:"members" as const,label:"Membros",show:true}];
  return <div className="fixed inset-0 z-50 flex bg-black/85 backdrop-blur-sm">
    <aside className="hidden w-60 shrink-0 border-r border-border bg-sidebar p-4 sm:block"><p className="mb-5 font-display text-sm font-black text-primary">ESPANCORD</p>{tabs.filter(t=>t.show).map(t=><button key={t.id} onClick={()=>setTab(t.id)} className={`mb-1 flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold ${tab===t.id?"bg-primary/10 text-primary":"text-muted-foreground hover:bg-secondary"}`}>{t.id==="roles"?<Shield className="h-4 w-4"/>:t.id==="members"?<Users className="h-4 w-4"/>:<Settings className="h-4 w-4"/>}{t.label}</button>)}</aside>
    <div className="flex min-w-0 flex-1 flex-col"><header className="flex h-16 items-center border-b border-border px-4 sm:px-8"><div><h2 className="font-display text-lg font-bold">Gerenciar servidor</h2><p className="text-xs text-muted-foreground">Canais, cargos, membros e permissões</p></div><button onClick={onClose} className="ml-auto rounded-full border border-border p-2"><X className="h-5 w-5"/></button></header><div className="flex gap-2 overflow-x-auto border-b border-border p-2 sm:hidden">{tabs.filter(t=>t.show).map(t=><button key={t.id} onClick={()=>setTab(t.id)} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${tab===t.id?"bg-primary text-primary-foreground":"bg-secondary"}`}>{t.label}</button>)}</div>
      <div className="flex-1 overflow-y-auto p-4 sm:p-8"><div className="mx-auto max-w-4xl">
        {tab==="server"&&canServer&&<><Head title="Visão geral" text="Identidade principal do servidor."/><div className="mt-5 space-y-4 rounded-2xl border border-border bg-card p-5"><input className={field} value={settings.name} onChange={e=>setSettings({...settings,name:e.target.value})}/><textarea className={field} rows={3} value={settings.description} onChange={e=>setSettings({...settings,description:e.target.value})}/><div className="flex items-center gap-3"><input type="color" className="h-10 w-14" value={settings.accent_color} onChange={e=>setSettings({...settings,accent_color:e.target.value})}/><span className="text-sm text-muted-foreground">Cor de destaque</span></div><button onClick={()=>void saveServer()} className="rounded-lg bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground">Salvar</button></div></>}
        {tab==="channels"&&canChannels&&<><Head title="Canais" text="Crie canais de texto/voz e bloqueie por cargo."/><div className="mt-5 space-y-4 rounded-2xl border border-border bg-card p-5"><div className="flex items-center"><b>{channelId?"Editar canal":"Novo canal"}</b>{channelId&&<button onClick={resetChannel} className="ml-auto text-xs text-muted-foreground">Cancelar</button>}</div><input className={field} value={channelName} onChange={e=>setChannelName(e.target.value)} placeholder="nome-do-canal"/><div className="grid gap-3 sm:grid-cols-2"><select className={field} value={channelType} onChange={e=>setChannelType(e.target.value as "texto"|"voz")}><option value="texto">Texto</option><option value="voz">Voz / live</option></select><select className={field} value={minRole} onChange={e=>setMinRole(e.target.value as AppRole)}>{ROLE_ORDER.map(r=><option key={r} value={r}>Cargo-base: {ROLE_LABEL[r]} ou acima</option>)}</select></div><div><p className="text-xs font-bold uppercase text-muted-foreground">Cargos específicos permitidos</p><p className="mt-1 text-xs text-muted-foreground">Se marcar cargos, só quem tiver um deles verá/entrará no canal. Admins sempre entram.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{roles.length?roles.map(r=><label key={r.id} className="flex items-center gap-3 rounded-lg border border-border p-3"><input type="checkbox" checked={allowed.includes(r.id)} onChange={e=>setAllowed(e.target.checked?[...allowed,r.id]:allowed.filter(id=>id!==r.id))}/><span className="h-3 w-3 rounded-full" style={{backgroundColor:r.color}}/><span className="text-sm font-semibold">{r.name}</span></label>):<button onClick={()=>setTab("roles")} className="rounded-lg border border-dashed border-primary/40 p-3 text-left text-sm font-semibold text-primary">+ Criar um cargo primeiro</button>}</div></div><button onClick={()=>void saveChannel()} className="w-full rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">{channelId?"Salvar canal":"Criar canal"}</button></div><div className="mt-4 space-y-2">{channels.map(c=><div key={c.id} className="flex items-center gap-3 rounded-xl border border-border bg-card p-3">{c.type==="voz"?<Volume2 className="h-4 w-4 text-primary"/>:<Hash className="h-4 w-4"/>}<div className="min-w-0 flex-1"><b className="block truncate text-sm">{c.name}</b><span className="text-[10px] text-muted-foreground">{ROLE_LABEL[c.min_role]}{channelAccess[c.id]?.length?` • ${channelAccess[c.id].length} cargo(s)`:""}</span></div><button onClick={()=>editChannel(c)} className="p-2 text-muted-foreground hover:text-primary"><Pencil className="h-4 w-4"/></button><button onClick={()=>void removeChannel(c.id)} className="p-2 text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4"/></button></div>)}</div></>}
        {tab==="roles"&&canRoles&&<><Head title="Cargos" text="Crie cargos, cores e permissões como no Discord."/><div className="mt-5 grid gap-4 lg:grid-cols-[230px_1fr]"><div className="space-y-2"><button onClick={resetRole} className="flex w-full items-center gap-2 rounded-lg border border-dashed border-primary/40 px-3 py-2 text-sm font-bold text-primary"><Plus className="h-4 w-4"/>Novo cargo</button>{roles.map(r=><button key={r.id} onClick={()=>editRole(r)} className="flex w-full items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-left"><span className="h-3 w-3 rounded-full" style={{backgroundColor:r.color}}/><span className="flex-1 truncate text-sm font-semibold">{r.name}</span><Pencil className="h-3.5 w-3.5"/></button>)}</div><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center"><b>{roleId?"Editar cargo":"Novo cargo"}</b>{roleId&&<button onClick={()=>void removeRole(roleId)} className="ml-auto text-destructive"><Trash2 className="h-4 w-4"/></button>}</div><div className="mt-4 space-y-3"><input className={field} value={roleName} onChange={e=>setRoleName(e.target.value)} placeholder="VIP, Equipe, Trader..."/><div className="flex items-center gap-3"><input type="color" className="h-10 w-14" value={roleColor} onChange={e=>setRoleColor(e.target.value)}/><span className="rounded border px-3 py-1 text-xs font-bold" style={{color:roleColor,borderColor:roleColor}}>{roleName||"Cargo"}</span></div>{CUSTOM_PERMISSIONS.map(p=><label key={p} className="flex items-start gap-3 rounded-lg border border-border bg-background/50 p-3"><input type="checkbox" className="mt-1" checked={permissions.includes(p)} onChange={e=>setPermissions(e.target.checked?[...permissions,p]:permissions.filter(x=>x!==p))}/><div><p className="text-sm font-semibold">{CUSTOM_PERMISSION_LABEL[p].title}</p><p className="text-xs text-muted-foreground">{CUSTOM_PERMISSION_LABEL[p].description}</p></div></label>)}<button onClick={()=>void saveRole()} className="w-full rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">{roleId?"Salvar cargo":"Criar cargo"}</button></div></div></div></>}
        {tab==="members"&&<><Head title="Membros" text="Clique para administrar cargos e moderação."/><div className="mt-5 overflow-hidden rounded-2xl border border-border bg-card">{members.map(m=><button key={m.id} onClick={()=>onMember(m.id)} className="flex w-full items-center gap-3 border-b border-border/60 px-4 py-3 text-left last:border-0 hover:bg-secondary/40"><Avatar m={m}/><div className="min-w-0 flex-1"><b className="block truncate text-sm">{m.display_name}</b><div className="mt-1 flex flex-wrap gap-1"><span className={`rounded border px-1.5 text-[9px] uppercase ${ROLE_STYLE[topRole(m.roles)]}`}>{ROLE_LABEL[topRole(m.roles)]}</span>{m.customRoles.map(r=><span key={r.id} className="rounded border px-1.5 text-[9px] font-bold" style={{color:r.color}}>{r.name}</span>)}</div></div>{m.status!=="active"&&<span className="text-xs font-bold text-destructive">{m.status==="banned"?"BANIDO":"EXPULSO"}</span>}</button>)}</div></>}
      </div></div>
    </div>
  </div>;
}
function Head({title,text}:{title:string;text:string}){return <div><h3 className="font-display text-xl font-bold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{text}</p></div>}
function Avatar({m}:{m:Member}){return m.avatar_url?<img src={m.avatar_url} alt="" className="h-10 w-10 rounded-full object-cover" referrerPolicy="no-referrer"/>:<div className="flex h-10 w-10 items-center justify-center rounded-full bg-secondary font-bold">{m.display_name[0]?.toUpperCase()}</div>}
