import { useEffect,useRef,useState,type ReactNode,type RefObject } from "react";
import { Mic,MicOff,MonitorUp,PhoneOff,Radio,RefreshCw,Video,VideoOff } from "lucide-react";
import { toast } from "sonner";
import type { RealtimeChannel } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";
const TURN_URL=import.meta.env.VITE_TURN_URL as string|undefined,TURN_USERNAME=import.meta.env.VITE_TURN_USERNAME as string|undefined,TURN_CREDENTIAL=import.meta.env.VITE_TURN_CREDENTIAL as string|undefined;
const ICE:RTCConfiguration={iceServers:[{urls:"stun:stun.l.google.com:19302"},{urls:"stun:global.stun.twilio.com:3478"},...(TURN_URL&&TURN_USERNAME&&TURN_CREDENTIAL?[{urls:TURN_URL,username:TURN_USERNAME,credential:TURN_CREDENTIAL}]:[])],iceCandidatePoolSize:10};
type Presence={name:string;joined:boolean;sharing:boolean;camOn:boolean;micOn:boolean};
type Peer={id:string;name:string;stream:MediaStream;hasVideo:boolean;sharing:boolean;connected:boolean};
type Signal={to:string;from:string;name:string;type?:"request-offer";sdp?:RTCSessionDescriptionInit;candidate?:RTCIceCandidateInit;restartIce?:boolean};
export function VoiceRoom({channelId,channelName,userId,userName,autoJoin=true,onJoinedChange}:{channelId:string;channelName:string;userId:string;userName:string;autoJoin?:boolean;onJoinedChange?:(joined:boolean)=>void}){
 const [ready,setReady]=useState(false),[joined,setJoined]=useState(false),[micOn,setMicOn]=useState(false),[camOn,setCamOn]=useState(false),[sharing,setSharing]=useState(false),[peers,setPeers]=useState<Peer[]>([]);
 const local=useRef(new MediaStream()),localVideo=useRef<HTMLVideoElement>(null),pcs=useRef(new Map<string,RTCPeerConnection>()),streams=useRef(new Map<string,MediaStream>()),ice=useRef(new Map<string,RTCIceCandidateInit[]>()),rt=useRef<RealtimeChannel|null>(null),joinedRef=useRef(false),joining=useRef(false),autoTried=useRef(false),callback=useRef(onJoinedChange),presence=useRef<Presence>({name:userName,joined:false,sharing:false,camOn:false,micOn:false});
 useEffect(()=>{callback.current=onJoinedChange},[onJoinedChange]);
 function upsert(id:string,patch:Partial<Peer>){setPeers(list=>{const found=list.find(p=>p.id===id);if(found)return list.map(p=>p.id===id?{...p,...patch}:p);const stream=streams.current.get(id)??patch.stream??new MediaStream();streams.current.set(id,stream);return[...list,{id,name:"Membro",stream,hasVideo:false,sharing:false,connected:false,...patch}]})}
 function track(p:Partial<Presence>){presence.current={...presence.current,...p,name:userName};if(rt.current)void rt.current.track(presence.current)}
 function signal(to:string,p:Omit<Signal,"to"|"from"|"name">){return rt.current?.send({type:"broadcast",event:"signal",payload:{to,from:userId,name:userName,...p} satisfies Signal})}
 function sender(pc:RTCPeerConnection,kind:"audio"|"video"){return pc.getTransceivers().find(t=>t.receiver.track.kind===kind)?.sender}
 function replace(kind:"audio"|"video",media:MediaStreamTrack|null){pcs.current.forEach(pc=>void sender(pc,kind)?.replaceTrack(media))}
 async function flush(id:string,pc:RTCPeerConnection){for(const c of ice.current.get(id)??[]){try{await pc.addIceCandidate(c)}catch{}}ice.current.delete(id)}
 async function offer(id:string,pc:RTCPeerConnection,restartIce=false){if(pc.signalingState!=="stable")return;try{const sdp=await pc.createOffer({iceRestart:restartIce});await pc.setLocalDescription(sdp);await signal(id,{sdp:pc.localDescription??sdp,restartIce})}catch{}}
 function peer(id:string,name:string){const old=pcs.current.get(id);if(old){upsert(id,{name});return old}const pc=new RTCPeerConnection(ICE),stream=new MediaStream();pcs.current.set(id,pc);streams.current.set(id,stream);upsert(id,{name,stream});const a=pc.addTransceiver("audio",{direction:"sendrecv"}),v=pc.addTransceiver("video",{direction:"sendrecv"});void a.sender.replaceTrack(local.current.getAudioTracks()[0]??null);void v.sender.replaceTrack(local.current.getVideoTracks()[0]??null);pc.ontrack=e=>{if(!stream.getTracks().some(t=>t.id===e.track.id))stream.addTrack(e.track);const refresh=()=>upsert(id,{stream,hasVideo:stream.getVideoTracks().some(t=>t.readyState==="live"&&!t.muted)});e.track.addEventListener("unmute",refresh);e.track.addEventListener("mute",refresh);e.track.addEventListener("ended",refresh);refresh()};pc.onicecandidate=e=>{if(e.candidate)void signal(id,{candidate:e.candidate.toJSON()})};pc.onconnectionstatechange=()=>{const connected=pc.connectionState==="connected";upsert(id,{connected});if(["failed","disconnected"].includes(pc.connectionState))window.setTimeout(()=>{if(["failed","disconnected"].includes(pc.connectionState)){if(userId<id)void offer(id,pc,true);else void signal(id,{type:"request-offer",restartIce:true})}},900);if(pc.connectionState==="closed"){pcs.current.delete(id);streams.current.delete(id);setPeers(x=>x.filter(p=>p.id!==id))}};return pc}
 function sync(ch:RealtimeChannel){const state=ch.presenceState<Presence>(),active:string[]=[];Object.entries(state).forEach(([id,values])=>{if(id===userId)return;const m=values?.[0] as Presence|undefined;if(!m?.joined)return;active.push(id);upsert(id,{name:m.name??"Membro",sharing:!!m.sharing});if(joinedRef.current){const pc=peer(id,m.name??"Membro");if(userId<id&&pc.signalingState==="stable"&&!pc.localDescription)void offer(id,pc)}});pcs.current.forEach((pc,id)=>{if(!joinedRef.current||!active.includes(id)){pc.close();pcs.current.delete(id);streams.current.delete(id);ice.current.delete(id);setPeers(x=>x.filter(p=>p.id!==id))}})}
 async function reconnect(){const state=rt.current?.presenceState<Presence>()??{};await Promise.all(Object.entries(state).filter(([id,v])=>id!==userId&&v?.[0]?.joined).map(([id,v])=>{const name=(v?.[0] as Presence|undefined)?.name??"Membro",pc=peer(id,name);return userId<id?offer(id,pc,true):signal(id,{type:"request-offer",restartIce:true})}))}
 useEffect(()=>{const ch=supabase.channel(`voice-${channelId}`,{config:{presence:{key:userId}}});rt.current=ch;ch.on("broadcast",{event:"signal"},async({payload})=>{const s=payload as Signal;if(s.to!==userId||!joinedRef.current)return;const pc=peer(s.from,s.name??"Membro");try{if(s.type==="request-offer"){if(userId<s.from)await offer(s.from,pc,!!s.restartIce);return}if(s.sdp){if(s.sdp.type==="offer"){if(pc.signalingState!=="stable"){if(userId<s.from)return;await pc.setLocalDescription({type:"rollback"})}await pc.setRemoteDescription(s.sdp);await flush(s.from,pc);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await signal(s.from,{sdp:pc.localDescription??answer})}else if(s.sdp.type==="answer"&&pc.signalingState==="have-local-offer"){await pc.setRemoteDescription(s.sdp);await flush(s.from,pc)}return}if(s.candidate){if(pc.remoteDescription)await pc.addIceCandidate(s.candidate);else ice.current.set(s.from,[...(ice.current.get(s.from)??[]),s.candidate])}}catch{if(userId<s.from)void offer(s.from,pc,true);else void signal(s.from,{type:"request-offer",restartIce:true})}});ch.on("presence",{event:"sync"},()=>sync(ch));ch.subscribe(async status=>{if(status==="SUBSCRIBED"){setReady(true);await ch.track(presence.current);sync(ch)}});return()=>{joinedRef.current=false;callback.current?.(false);local.current.getTracks().forEach(t=>t.stop());pcs.current.forEach(pc=>pc.close());pcs.current.clear();streams.current.clear();ice.current.clear();void supabase.removeChannel(ch);rt.current=null}},[channelId,userId,userName]);
 async function tone(join:boolean){try{const AC=window.AudioContext??(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AC)return;const c=new AC(),g=c.createGain();g.gain.value=.05;g.connect(c.destination);(join?[392,523]:[523,392]).forEach((f,i)=>{const o=c.createOscillator();o.frequency.value=f;o.connect(g);o.start(c.currentTime+i*.09);o.stop(c.currentTime+i*.09+.08)});window.setTimeout(()=>void c.close(),350)}catch{}}
 async function enter(){if(joining.current||joinedRef.current)return;joining.current=true;let mic=false;try{try{const media=await navigator.mediaDevices.getUserMedia({audio:true}),audio=media.getAudioTracks()[0];if(audio){local.current.addTrack(audio);mic=true}}catch{toast.warning("Você entrou sem microfone. Libere a permissão para falar.")}joinedRef.current=true;presence.current.joined=true;setJoined(true);setMicOn(mic);track({joined:true,micOn:mic});callback.current?.(true);if(rt.current)sync(rt.current);await tone(true)}finally{joining.current=false}}
 useEffect(()=>{if(autoJoin&&ready&&!joined&&!autoTried.current){autoTried.current=true;void enter()}},[autoJoin,ready,joined]);
 async function toggleMic(){const audio=local.current.getAudioTracks()[0];if(audio){audio.enabled=!audio.enabled;setMicOn(audio.enabled);track({micOn:audio.enabled});return}try{const media=await navigator.mediaDevices.getUserMedia({audio:true}),next=media.getAudioTracks()[0];if(!next)return;local.current.addTrack(next);replace("audio",next);setMicOn(true);track({micOn:true});await reconnect()}catch{toast.error("Não consegui acessar seu microfone.")}}
 function clearVideo(){local.current.getVideoTracks().forEach(t=>{t.stop();local.current.removeTrack(t)})}
 async function stopVideo(){clearVideo();replace("video",null);setCamOn(false);setSharing(false);track({camOn:false,sharing:false});if(localVideo.current)localVideo.current.srcObject=local.current;await reconnect()}
 async function startVideo(screen:boolean){try{const media=screen?await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:30,max:30}},audio:false}):await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720}}}),next=media.getVideoTracks()[0];if(!next)return;clearVideo();local.current.addTrack(next);replace("video",next);next.onended=()=>void stopVideo();setCamOn(!screen);setSharing(screen);track({camOn:!screen,sharing:screen});if(localVideo.current)localVideo.current.srcObject=local.current;await reconnect()}catch{toast.error(screen?"Transmissão de tela cancelada.":"Não consegui acessar sua câmera.")}}
 async function leave(){track({joined:false,micOn:false,camOn:false,sharing:false});joinedRef.current=false;callback.current?.(false);local.current.getTracks().forEach(t=>t.stop());local.current=new MediaStream();pcs.current.forEach(pc=>pc.close());pcs.current.clear();streams.current.clear();ice.current.clear();setPeers([]);setJoined(false);setMicOn(false);setCamOn(false);setSharing(false);await tone(false)}
 if(!joined)return <div className="flex flex-1 flex-col items-center justify-center gap-4 p-6 text-center"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10"><RefreshCw className="h-6 w-6 animate-spin text-primary"/></div><div><h2 className="font-display text-lg font-bold">Entrando em {channelName}</h2><p className="mt-1 text-sm text-muted-foreground">Conectando áudio e membros da sala…</p></div>{!ready&&<span className="text-xs text-muted-foreground">Sincronizando o canal…</span>}</div>;
 return <div className="flex min-h-0 flex-1 flex-col">{sharing&&<div className="flex items-center justify-center gap-2 border-b border-destructive/30 bg-destructive/10 py-2 text-xs font-bold text-destructive"><Radio className="h-3.5 w-3.5 animate-pulse"/>VOCÊ ESTÁ AO VIVO</div>}<div className="grid flex-1 grid-cols-1 gap-3 overflow-y-auto p-4 md:grid-cols-2 xl:grid-cols-3"><Tile name={`${userName} (você)`} stream={local.current} hasVideo={camOn||sharing} sharing={sharing} connected muted videoRef={localVideo}/>{peers.map(p=><Tile key={p.id} name={p.name} stream={p.stream} hasVideo={p.hasVideo} sharing={p.sharing} connected={p.connected}/>)}</div><div className="flex items-center justify-center gap-3 border-t border-border bg-sidebar p-4"><Ctrl active={micOn} label="Microfone" onClick={()=>void toggleMic()}>{micOn?<Mic className="h-5 w-5"/>:<MicOff className="h-5 w-5"/>}</Ctrl><Ctrl active={camOn} label="Câmera" onClick={()=>camOn?void stopVideo():void startVideo(false)}>{camOn?<Video className="h-5 w-5"/>:<VideoOff className="h-5 w-5"/>}</Ctrl><Ctrl active={sharing} label="Transmitir tela" onClick={()=>sharing?void stopVideo():void startVideo(true)}><MonitorUp className="h-5 w-5"/></Ctrl><button onClick={()=>void leave()} title="Desconectar" className="rounded-full bg-destructive p-3 text-white"><PhoneOff className="h-5 w-5"/></button></div></div>
}
function Ctrl({active,label,onClick,children}:{active:boolean;label:string;onClick:()=>void;children:ReactNode}){return <button onClick={onClick} title={label} className={`rounded-full p-3 ${active?"bg-primary text-primary-foreground":"bg-secondary text-foreground hover:bg-muted"}`}>{children}</button>}
function Tile({name,stream,hasVideo,sharing,connected,muted,videoRef}:{name:string;stream:MediaStream;hasVideo:boolean;sharing:boolean;connected:boolean;muted?:boolean;videoRef?:RefObject<HTMLVideoElement|null>}){const own=useRef<HTMLVideoElement>(null),ref=videoRef??own,[blocked,setBlocked]=useState(false);async function play(){if(!ref.current)return;try{await ref.current.play();setBlocked(false)}catch{setBlocked(true)}}useEffect(()=>{if(ref.current){ref.current.srcObject=stream;if(hasVideo)void play()}},[stream,hasVideo]);return <div className={`relative flex aspect-video min-h-48 items-center justify-center overflow-hidden rounded-xl border bg-card ${sharing?"border-destructive/60":"border-border"}`}><video ref={ref} autoPlay playsInline muted={muted} onLoadedMetadata={()=>void play()} className={`h-full w-full ${sharing?"object-contain":"object-cover"} ${hasVideo?"":"hidden"}`}/>{!hasVideo&&<div className="flex flex-col items-center gap-3"><div className="flex h-20 w-20 items-center justify-center rounded-full bg-secondary text-2xl font-bold">{name[0]?.toUpperCase()}</div>{sharing&&<span className="text-xs font-semibold text-muted-foreground">{connected?"Carregando transmissão…":"Conectando transmissão…"}</span>}</div>}{blocked&&hasVideo&&<button onClick={()=>void play()} className="absolute inset-0 z-10 flex items-center justify-center bg-black/55 text-sm font-bold text-white">Clique para iniciar vídeo e áudio</button>}<span className="absolute bottom-2 left-2 flex items-center gap-2 rounded bg-black/70 px-2 py-1 text-xs text-white">{sharing&&<Radio className="h-3 w-3 text-red-400"/>}{name}{sharing&&<b className="text-red-300">AO VIVO</b>}</span></div>}
